import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/page";
import Footer from "./components/Footer/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata  = {
  title: "Contact Us - NSS Education",
  description: "Reach out for courses, admissions, and support.",
  
  keywords: ["education", "courses", "contact", "NSS", "Medical Courses",
"Health Sanitary Inspector",
"Paramedical Courses",
"X-Ray Technician",
"DMLT (Diploma in Medical Laboratory Technology)",
"P.G. DMLT",],

  openGraph: {
    title: "Contact NSS Education",
    description: "We are here to help you.",
    url: "https://nsseducation.com/contact",
    siteName: "NSS Education",
    images: [
      {
        url: "https://nsseducation.com/logo.png",
        width: 1200,
        height: 630,
      },
    ],
    type: "website",
  },

  twitter: {
    card: "summary_large_image",
    title: "Contact NSS Education",
    description: "Reach us easily",
    images: ["https://nsseducation.com/logo.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
         <Navbar />
        <main>
           {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
